export const sampleProducts = [
  {
    category: 1,
    name: "오이",
    originPrice: 2000,
    salePrice: 1500,
    writer: { name: "명란젓코난", level: 3, image: require("@assets/sample/userPhoto.png") },
    store: { name: "망원시장 송이네 청과", address: "" },
    image: require("@assets/sample/cucumber.png"),
  },
  {
    category: 1,
    name: "애호박",
    originPrice: 2000,
    salePrice: 1000,
    writer: { name: "명란젓코난", level: 3, image: require("@assets/sample/userPhoto.png") },
    store: { name: "망원시장 송이네 청과", address: "" },
    image: require("@assets/sample/zucchini.png"),
  },
  {
    category: 1,
    name: "오렌지",
    originPrice: 10000,
    salePrice: 5000,
    writer: { name: "명란젓코난", level: 3, image: require("@assets/sample/userPhoto.png") },
    store: { name: "망원시장 송이네 청과", address: "" },
    image: require("@assets/sample/orange.png"),
  },
  {
    category: 1,
    name: "무",
    originPrice: 2000,
    salePrice: 1000,
    writer: { name: "명란젓코난", level: 3, image: require("@assets/sample/userPhoto.png") },
    store: { name: "망원시장 송이네 청과", address: "" },
    image: require("@assets/sample/radish.png"),
  },
  {
    category: 1,
    name: "대파",
    originPrice: 1000,
    salePrice: 500,
    writer: { name: "명란젓코난", level: 3, image: require("@assets/sample/userPhoto.png") },
    store: { name: "망원시장 송이네 청과", address: "" },
    image: require("@assets/sample/springOnion.png"),
  },
  {
    category: 1,
    name: "딸기",
    originPrice: 10000,
    salePrice: 8000,
    writer: { name: "명란젓코난", level: 3, image: require("@assets/sample/userPhoto.png") },
    store: { name: "망원시장 송이네 청과", address: "" },
    image: require("@assets/sample/strawberry.png"),
  },
  {
    category: 2,
    name: "조기구이",
    originPrice: 15000,
    salePrice: 10000,
    writer: { name: "노맛개복치", level: 1, image: require("@assets/sample/userPhoto.png") },
    store: { name: "망원시장 물고기왕", address: "" },
    image: require("@assets/sample/joki.png"),
  },
  {
    category: 2,
    name: "멍게",
    originPrice: 10000,
    salePrice: 8000,
    writer: { name: "노맛개복치", level: 1, image: require("@assets/sample/userPhoto.png") },
    store: { name: "망원시장 물고기왕", address: "" },
    image: require("@assets/sample/mung.png"),
  },
  {
    category: 2,
    name: "오징어",
    originPrice: 20000,
    salePrice: 10000,
    writer: { name: "노맛개복치", level: 1, image: require("@assets/sample/userPhoto.png") },
    store: { name: "망원시장 물고기왕", address: "" },
    image: require("@assets/sample/squid.png"),
  },
  {
    category: 2,
    name: "쭈꾸미",
    originPrice: 20000,
    salePrice: 10000,
    writer: { name: "노맛개복치", level: 1, image: require("@assets/sample/userPhoto.png") },
    store: { name: "망원시장 물고기왕", address: "" },
    image: require("@assets/sample/zzu.png"),
  },
  {
    category: 2,
    name: "생물낙지",
    originPrice: 15000,
    salePrice: 10000,
    writer: { name: "노맛개복치", level: 1, image: require("@assets/sample/userPhoto.png") },
    store: { name: "망원시장 물고기왕", address: "" },
    image: require("@assets/sample/nak.png"),
  },
];
